# Generated by Django 3.1.7 on 2021-03-25 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('cafienated', models.BooleanField()),
                ('coffeeshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandbox.coffeeshop', verbose_name='what shop its in')),
            ],
        ),
        migrations.CreateModel(
            name='Barrista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('CoffeeShop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandbox.coffeeshop', verbose_name='employer')),
            ],
        ),
    ]
